[package]
name = "nirman-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nirman-artifacts = { path = "../nirman-artifacts" }
nirman-android = { path = "../nirman-android" }
nirman-preview = { path = "../nirman-preview" }
nirman-domain = { path = "../nirman-domain" }
nirman-project = { path = "../nirman-project" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
nirman-control-plane = { path = "../nirman-control-plane" }
